[package]
name = "cinewana-metadata"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
cinewana-core = { path = "../cinewana-core" }
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
